name: 'Create Azure DevOps Work Item (Reusable Workflow)'
description: |
  This repository provides a reusable workflow for creating work items in Azure DevOps from GitHub issues or workflow dispatch.
  
  To use, call the workflow in `.github/workflows/create-workitem-with-sp.yml` via `workflow_call` or `workflow_dispatch`.

branding:
  icon: 'check-circle'
  color: 'blue'
