name: 'Create ADO User Story'
description: 'Creates a user story in Azure DevOps from a GitHub issue'
inputs:
  ado-org:
    required: true
    description: 'Azure DevOps organization'
  ado-project:
    required: true
    description: 'Azure DevOps project'
  ado-epic-id:
    required: true
    description: 'Azure DevOps Epic ID'
  ado-pat:
    required: true
    description: 'Azure Personal Access Token'
  ado-work-item-type:
    required: false
    description: 'Azure DevOps Work Item Type (e.g., User Story, Product Backlog Item, Bug)'
    default: 'User Story'
  ado-area:
    required: true
    description: 'Azure DevOps Area Path for the work item'
  ado-tags:
    required: false
    description: 'Comma-separated list of tags to apply to the work item'
runs:
  using: 'composite'
  steps:
    - run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        ISSUE_BODY="${{ github.event.issue.body }}"

        # This setting the title
        JSON_PAYLOAD="[{\"op\":\"add\",\"path\":\"/fields/System.Title\",\"value\":\"$ISSUE_TITLE\"}"

        # This is setting the body
        JSON_PAYLOAD+=" ,{\"op\":\"add\",\"path\":\"/fields/System.Description\",\"value\":\"$ISSUE_BODY\"}"

        # This is setting and adding the tags
        TAGS_VALUE="${{ inputs.ado-tags }}"
        if [ -z "$TAGS_VALUE" ]; then
          JSON_PAYLOAD+=" ,{\"op\":\"add\",\"path\":\"/fields/System.Tags\",\"value\":\"$TAGS_VALUE\"}"
        fi

        # This is setting the area path/board this will go on
        JSON_PAYLOAD+=" ,{\"op\":\"add\",\"path\":\"/fields/System.AreaPath\",\"value\":\"${{ inputs.ado-area }}\"}"

        # This is adding the relationship to the parent
        JSON_PAYLOAD+=" ,{\"op\":\"add\",\"path\":\"/relations/-\",\"value\":{\"rel\":\"System.LinkTypes.Hierarchy-Reverse\",\"url\":\"https://dev.azure.com/${{ inputs.ado-org }}/${{ inputs.ado-project }}/_apis/wit/workItems/${{ inputs.ado-epic-id }}\"}}]"
        echo "$JSON_PAYLOAD" > payload.json
        WORK_ITEM_TYPE_ENC=$(echo -n "${{ inputs.ado-work-item-type }}" | sed 's/ /%20/g')
        CREATE_URL="https://dev.azure.com/${{ inputs.ado-org }}/${{ inputs.ado-project }}/_apis/wit/workitems/\$${WORK_ITEM_TYPE_ENC}?api-version=7.0"
        RESPONSE=$(curl --silent --show-error -X PATCH \
          -H "Content-Type: application/json-patch+json" \
          -H "Authorization: Basic $(echo -n :${{ inputs.ado-pat }} | base64 | tr -d '\n')" \
          --data-binary @payload.json \
          "$CREATE_URL")
        echo "$RESPONSE"
        WORK_ITEM_ID=$(echo "$RESPONSE" | grep -o '"id":[0-9]*' | head -n1 | grep -o '[0-9]*')
        if [ -n "$WORK_ITEM_ID" ]; then
          STORY_URL="https://dev.azure.com/${{ inputs.ado-org }}/${{ inputs.ado-project }}/_workitems/edit/$WORK_ITEM_ID"
          echo "Created work item: $STORY_URL"
        else
          echo "Failed to parse work item ID from response."
        fi
      shell: bash
