name: 'Create ADO Work Item using Service Principal'

on:
  # You can customize these triggers as needed
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the work item'
        required: true
        default: 'New Work Item'
      description:
        description: 'Description of the work item'
        required: false
        default: ''
      type:
        description: 'Type of the work item (e.g., User Story, Task, Bug)'
        required: true
        default: 'User Story'
      ado-organization:
        description: 'Azure DevOps organization'
        required: false
        default: 'SECURAInsurance'

  workflow_call:
    inputs:
      title:
        description: 'Title of the work item'
        required: true
        type: string
      description:
        description: 'Description of the work item'
        required: false
        type: string
      type:
        description: 'Type of the work item (e.g., User Story, Task, Bug)'
        required: true
        type: string
      ado-organization:
        description: 'Azure DevOps organization'
        required: false
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  create-work-item:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Checkout Token Generator
        uses: actions/checkout@v3
        with:
          repository: hunterkleppek/get-accesstoken-from-serviceprinciple-workflow
          path: get-token-repo
      
      - name: Get Azure DevOps Token
        id: get-token
        uses: ./get-token-repo
        with:
          client-id: ${{ secrets.ADO_SP_CLIENT_ID }}
          tenant-id: ${{ secrets.ADO_SP_TENANT_ID }}
          client-secret: ${{ secrets.ADO_SP_CLIENT_SECRET }}
          organization: ${{ github.event.inputs.ado-organization || 'SECURAInsurance' }}
      
      - name: Parse Description
        id: work_item_details
        shell: pwsh
        run: |
          $outputs = ${{ github.action_path }}/PowerShell/parse-issue-details.ps1 `
            -IssueTitle "${{ github.event.inputs.title }}" `
            -IssueBody "${{ github.event.inputs.description }}"

      - name: Create ADO Work Item from Remote Repository
        if: github.event_name == 'workflow_call'
        shell: pwsh
        run: |
          $title = "${{ steps.work-item-details.outputs.title }}"
          if (-not $title) { throw 'Title is required and cannot be empty.' }

          $description = "${{ steps.work-item-details.outputs.description }}"
          if ($null -eq $description -or $description -eq "") { $description = "No description provided." }

          $project = "${{ steps.work-item-details.outputs.project }}"
          if (-not $project) { $project = "Suite" }

          $areaPath = "${{ steps.work-item-details.outputs.area }}"
          # Remove any surrounding single or double quotes
          $areaPath = $areaPath.Trim("'", '"')
          # Replace double backslashes with single backslash
          $areaPath = $areaPath -replace '\\{2}', '\\'
          if (-not $areaPath) { $areaPath = "Suite\\Integrations - 1" }

          $parentId = "${{ steps.work-item-details.outputs.parent }}"

          # Determine work item type from issue labels
          $labels = @()
          if ($env:GITHUB_EVENT_PATH) {
            $event = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json
            $labels = $event.issue.labels | ForEach-Object { $_.name }
          }
          $type = "User Story" # default
          if ($labels -contains "bug") { $type = "Bug" }
          elseif ($labels -contains "task") { $type = "Task" }
          elseif ($labels -contains "story") { $type = "User Story" }
          elseif ($labels -contains "feature") { $type = "Feature" }
          elseif ($labels -contains "epic") { $type = "Epic" }
          Write-Host "Labels: $($labels -join ', ')"
          Write-Host "Determined Work Item Type: $type"

          $result = ${{ github.action_path }}/PowerShell/create-ado-story.ps1 `
            -Organization "${{ github.event.inputs.ado-organization || 'SECURAInsurance' }}" `
            -Project $project `
            -BearerToken "${{ steps.get-token.outputs.token }}" `
            -IssueTitle $title `
            -IssueBody $description `
            -WorkItemType $type `
            -ParentId $parentId `
            -AreaPath $areaPath
          Write-Host "Script output: $result"
          $linkMatch = [regex]::Match($result, 'https?://\S+')
          if ($linkMatch.Success) {
            Write-Host "Work item link: $($linkMatch.Value)"
          }
      
      - name: Create ADO Work Item from Workflow
        if: github.event_name == 'workflow_dispatch'
        shell: pwsh
        run: |
          $title = "${{ github.event.inputs.title }}"
          if (-not $title) { throw 'Title is required and cannot be empty.' }

          $description = "${{ steps.work_item_details.outputs.description }}"
          if ($null -eq $description -or $description -eq "") { $description = "No description provided." }

          $project = "${{ steps.work_item_details.outputs.project }}"
          if (-not $project) { $project = "Suite" }

          $areaPath = "${{ steps.work_item_details.outputs.area }}"
          # Remove any surrounding single or double quotes
          $areaPath = $areaPath.Trim("'", '"')
          # Replace double backslashes with single backslash
          $areaPath = $areaPath -replace '\\{2}', '\\'
          if (-not $areaPath) { $areaPath = "Suite\\Integrations - 1" }

          $parentId = "${{ steps.work_item_details.outputs.parent }}"

          $result = ${{ github.action_path }}/PowerShell/create-ado-story.ps1 `
            -Organization "${{ github.event.inputs.ado-organization || 'SECURAInsurance' }}" `
            -Project $project `
            -BearerToken "${{ steps.get-token.outputs.token }}" `
            -IssueTitle $title `
            -IssueBody $description `
            -WorkItemType "${{ github.event.inputs.type }}" `
            -ParentId $parentId `
            -AreaPath $areaPath
          Write-Host "Script output: $result"
          $linkMatch = [regex]::Match($result, 'https?://\S+')
          if ($linkMatch.Success) {
            Write-Host "Work item link: $($linkMatch.Value)"
          }


